### ISSUE TITLE
[bug] Only 1 service is generated

### ISSUE THREAD

**Issue by bobbydeveaux** [score-spec/score-helm#28]
**Describe the bug**
When running `score-helm run -f score.yaml -o manifest.yaml`, it generates a file that is used by the 'score-helm-charts/workload' helm chart. However, despite my score.yaml file containing 2 services, the helm-chart creates a service in k8s as 1 service with 2 pods. 

**To Reproduce**
```
apiVersion: score.dev/v1b1

metadata:
  name: both

containers:
  backend:
    image: be:1.0.0

  frontend:
    image: fe:1.0.0

service:
  ports:
    frontend:
      port: 8080
      targetPort: 8080
    backend:
      port: 8000
      targetPort: 8000

resources:
  env:
    type: environment

  my-be-dns:
    type: dns

  my-fe-dns:
    type: dns

  bobby-bucket:
    type: s3

  backend-route:
    type: route
    params:
      path: /api
      port: 8000
      host: ${resources.my-be-dns.host}

  frontend-route:
    type: route
    params:
      path: /
      port: 8080
      host: ${resources.my-fe-dns.host}
```

`score-helm run -f score.yaml -o manifest.yaml`

` helm install test-app score-helm-charts/workload --values ./manifest.yaml`

**Expected behavior**
Would expect an 2 deployments within k8s - and 2 services running.
